fix: inherit with grandparent's class directly
Some devices cause error with super(BertTokenizer, self).__init__() as
TypeError: super(type, obj): obj must be an instance or subtype of type

cf. https://stackoverflow.com/questions/43016737/python-inheritance-how-to-call-grandparent-method